# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  
  #config.vm.hostname="ubuntu16-srv-c23515"

  #config.vm.synced_folder "../../../Documents/IMW", "/IMW"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
    config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8118E89F3A912897C070ADBF76221572C52609D
	 sudo touch /etc/apt/sources.list.d/docker.list
	 echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" |sudo tee -a /etc/apt/sources.list.d/docker.list
	 sudo apt-get update 
	 sudo apt-get install linux-image-extra-$(uname -r)  --assume-yes
	 sudo apt-get install docker-engine  --assume-yes --force-yes
	 echo "deb http://us.archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
	 sudo apt-get update
	 sudo apt-get install fleet --assume-yes
	 sudo curl -L  https://github.com/coreos/etcd/releases/download/v2.1.0-rc.0/etcd-v2.1.0-rc.0-linux-amd64.tar.gz -o etcd-v2.1.0-rc.0-linux-amd64.tar.gz
	 sudo tar xzvf etcd-v2.1.0-rc.0-linux-amd64.tar.gz
	 git config --global http.sslVerify false
    SHELL
end
